import {test} from "node:test";
import assert from "node:assert/strict";
import {computeTrend} from "../lib/trending";
import {localDate,validDate} from "../lib/dates";
import {validateGoal,validateValue,compareObservations} from "../lib/goalValidation";
import {validOutput,requestSchema} from "../lib/schemas";
import {sandboxedDocumentTab,generatedDocument} from "../lib/safeHtml";
import {weeklyMinutes} from "../lib/services";
import type {IEPGoal,ProgressLogEntry} from "../types/iep";
const goal:IEPGoal={id:"goal",goalText:"Reduce occurrences",category:"behavioral",baselineValue:10,targetValue:2,measurementUnit:"count",reviewDate:"2026-09-11",createdAt:"2026-09-01"};
const logs=(values:number[],dates=["2026-09-01","2026-09-11"]):ProgressLogEntry[]=>values.map((value,i)=>({id:String(i),profileId:"p",goalId:"goal",date:dates[i],value,createdAt:`2026-09-01T00:00:0${i}Z`}));
test("reduction goals classify attainment in the correct direction",()=>{assert.equal(computeTrend(goal,logs([10,12])).status,"off_track");assert.equal(computeTrend(goal,logs([4,1])).status,"on_track");});
test("increasing and maintenance goals remain meaningful",()=>{assert.equal(computeTrend({...goal,baselineValue:0,targetValue:10},logs([2,10])).status,"on_track");assert.equal(computeTrend({...goal,baselineValue:2},logs([2,2])).status,"on_track");assert.equal(computeTrend({...goal,baselineValue:2},logs([2,5])).status,"off_track");});
test("same-day data is not a trajectory and ties use timestamps",()=>{assert.equal(computeTrend(goal,logs([10,8],["2026-09-01","2026-09-01"])).status,"no_data");assert.ok(compareObservations(logs([10,8])[0],logs([10,8])[1])<0);});
test("projections obey percentage boundaries",()=>{const trend=computeTrend({...goal,measurementUnit:"%",baselineValue:0,targetValue:80,reviewDate:"2026-12-01"},logs([10,90]));assert.equal(trend.projectedValue,100);});
test("unit constraints reject invalid observations and dates",()=>{assert.ok(validateValue({measurementUnit:"%"},101));assert.ok(validateValue({measurementUnit:"trials",trialsDenominator:5},6));assert.ok(validateValue({measurementUnit:"minutes"},Infinity));assert.ok(validateGoal({...goal,reviewDate:"2026-02-30"}));assert.equal(validateGoal(goal),null);assert.equal(validDate("2024-02-29"),true);assert.equal(localDate(new Date(2026,8,6,20)),"2026-09-06");});
test("malformed provider preferences and material shapes are rejected",()=>{assert.equal(requestSchema.safeParse({providerPreferences:{text:["unknown"]}}).success,false);assert.equal(validOutput("slide_deck",{title:"Broken",slides:[{title:"Missing content"}]}),false);assert.equal(validOutput("mini_game",{title:"Quiz",theme:"",instructions:"Try",successMessage:"Done",engineType:"multiple_choice",quizQuestions:[]}),false);});
test("new-tab export keeps malicious HTML inside a sandbox",()=>{const hostile='<script>window.test=true</script><img src=x onerror="alert(1)">';const tab=sandboxedDocumentTab(hostile);assert.ok(tab.includes('sandbox=""'));assert.ok(!tab.includes('<script>'));assert.ok(tab.includes('&lt;script&gt;'));assert.ok(generatedDocument(hostile).includes("script-src 'none'"));});
test("weekly delivery excludes prior weeks and undated snapshots",()=>{assert.equal(weeklyMinutes([{date:"2026-09-06",minutes:10},{date:"2026-09-07",minutes:20},{date:"2026-09-13",minutes:30}],new Date(2026,8,7)),50);assert.equal(weeklyMinutes(undefined),0);});
