import {test} from "node:test";
import assert from "node:assert/strict";
import {NextRequest} from "next/server";
import {validOutput,type OutputKind} from "../lib/schemas";
import {localRequestAllowed} from "../lib/apiGuard";
// Route tests never spend provider credits or send student data externally.
for(const key of ["GEMINI_API_KEY","DEEPSEEK_API_KEY","MOONSHOT_API_KEY","OPENAI_API_KEY","MINIMAX_API_KEY","KLING_ACCESS_KEY","KLING_SECRET_KEY"]) delete process.env[key];
const student={initials:"TEST",grade:"3",eligibility:"Other",readingLevel:"Not specified",comprehensionLevel:"Not specified",communicationNeeds:[],sensoryConsiderations:[],interests:["Space"],preferredModality:[]};
const context={student,goal:{id:"g",goalText:"Solve equations",category:"academic",baselineValue:40,targetValue:80,measurementUnit:"%"},accommodations:[]};
const input={subjectArea:"Math",currentGradeLevel:"3",currentInstructionalLevel:"",currentAcademicSkills:"",areasOfStrength:"",areasOfWeakness:"Solving equations",assessmentResults:"40% on an observed probe",classroomPerformance:"",previousGoalsAndProgress:"",teacherObservations:""};
const spec={purpose:"practice",numQuestions:4,difficultyLevel:2,questionType:"mixed",readingLevel:"",scaffolding:"moderate",includeAnswerKey:true,includeVisualSupports:true,modifiedProblems:false,printable:true};
function request(path:string,body:unknown){return new NextRequest(`http://localhost:3000/api/${path}`,{method:"POST",headers:{"Content-Type":"application/json",Origin:"http://localhost:3000"},body:JSON.stringify(body)});}
test("all material local routes produce viewable schema-valid content",async()=>{
 for(const [name,kind] of [["slides","slide_deck"],["board-game","board_game"],["mini-game","mini_game"],["music","music"],["video","video_clip"],["narration","narration"],["worksheet","worksheet"],["instructional-unit","instructional_unit"]] as [string,OutputKind][]){const route=await import(`../app/api/generate/${name}/route.ts`);const res=await route.POST(request(`generate/${name}`,{context,spec}));const body=await res.json();assert.equal(res.status,200,`${name}: ${JSON.stringify(body)}`);assert.ok(validOutput(kind,body.content),`${name}: invalid fallback ${JSON.stringify(body.content)}`);}
});
test("planning never fabricates missing assessment evidence",async()=>{const plaafpRoute=await import("../app/api/planning/plaafp/route");const res=await plaafpRoute.POST(request("planning/plaafp",{student,input}));const body=await res.json();assert.equal(res.status,200);assert.ok(validOutput("plaafp",body.content));assert.ok(body.content.skillGaps.distanceFromGradeLevel.includes("has not been established"));const goalRoute=await import("../app/api/planning/iep-goal/route");const missing=await goalRoute.POST(request("planning/iep-goal",{student,plaafp:body.content,input:{...input,assessmentResults:""}}));assert.equal(missing.status,422);const valid=await goalRoute.POST(request("planning/iep-goal",{student,plaafp:body.content,input}));assert.equal(valid.status,200);assert.ok(validOutput("iep_goal",(await valid.json()).content));const upload=await plaafpRoute.POST(request("planning/plaafp",{student,input:{...input,rawNotes:"A report"}}));assert.equal(upload.status,422);});
test("first-day formats produce valid output",async()=>{const route=await import("../app/api/generate/first-day/route");for(const format of ["slide_deck","html_page","video_clip"] as OutputKind[]){const res=await route.POST(request("generate/first-day",{category:"teacher_intro",format,teacher:{name:"Test Teacher",roleTitle:"Teacher",subjectsOrGrades:"3",hobbiesAndInterests:[],funFacts:[]}}));const data=await res.json();assert.equal(res.status,200,JSON.stringify(data));assert.ok(validOutput(format,data.content),JSON.stringify(data.content));}});
test("invalid input returns 400 and cross-origin/exposed requests are denied",async()=>{const route=await import("../app/api/generate/slides/route");assert.equal((await route.POST(request("generate/slides",{context,providerPreferences:{text:["bogus"]}}))).status,400);assert.equal((await route.POST(request("generate/slides",{context:{student:{},goal:{}}}))).status,400);assert.equal(localRequestAllowed(new Request("https://public.example/api/generate/slides")),false);assert.equal(localRequestAllowed(new Request("http://localhost:3000/api/generate/slides",{headers:{Origin:"https://evil.example"}})),false);});
