"use client";
// components/CompareResultsModal.tsx — side-by-side comparison of the same
// material generated by several AI providers, so the teacher can pick the
// one they like best and discard the rest.

import { useState } from "react";
import { X, Eye, Trash2, CheckCircle2, AlertTriangle, Loader2 } from "lucide-react";
import { clsx } from "clsx";
import { providerDisplayName } from "@/lib/ai/providers";
import type { GenerationStatus } from "@/types/iep";

export interface ComparableMaterial {
  id: string;
  title: string;
  description: string;
  status: GenerationStatus;
  error?: string;
  provider?: string;
  modelUsed: string;
  generationCostEstimate?: number;
}

interface Props<T extends ComparableMaterial> {
  materials: T[];
  onView: (material: T) => void;
  onDelete: (material: T) => Promise<void>;
  onClose: () => void;
}

export default function CompareResultsModal<T extends ComparableMaterial>({
  materials,
  onView,
  onDelete,
  onClose
}: Props<T>) {
  const [items, setItems] = useState<T[]>(materials);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  async function handleDelete(material: T) {
    setDeletingId(material.id);
    try {
      await onDelete(material);
      setItems((prev) => prev.filter((m) => m.id !== material.id));
    } finally {
      setDeletingId(null);
    }
  }

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-3xl shadow-2xl w-full max-w-5xl max-h-[92vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        <div className="flex items-center justify-between px-6 py-5 border-b border-gray-200 bg-gradient-to-r from-slate-900 to-indigo-950 text-white">
          <div>
            <h2 className="text-lg font-black tracking-tight text-white">Compare Results</h2>
            <p className="text-xs text-indigo-200 mt-0.5">
              {items.length} version{items.length !== 1 ? "s" : ""} generated — open each to compare, then delete the ones you don't want.
            </p>
          </div>
          <button onClick={onClose} className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="overflow-y-auto flex-1 p-6 space-y-4">
          {items.length === 0 ? (
            <div className="text-center text-sm text-gray-500 py-12">
              All versions removed. Close this and generate again if you'd like.
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {items.map((m) => (
                <div
                  key={m.id}
                  className={clsx(
                    "rounded-2xl border-2 p-4 flex flex-col gap-3",
                    m.status === "error" ? "border-red-200 bg-red-50/50" : "border-gray-200 bg-white"
                  )}
                >
                  <div className="flex items-start justify-between gap-2">
                    <span className="px-2 py-0.5 rounded-full text-[10px] font-black uppercase bg-indigo-50 text-indigo-700 border border-indigo-200">
                      {providerDisplayName(m.provider)}
                    </span>
                    {m.status === "ready" && (
                      <span className="text-[10px] font-bold text-gray-400 bg-gray-100 px-2 py-0.5 rounded-md shrink-0">
                        ${(m.generationCostEstimate || 0).toFixed(3)}
                      </span>
                    )}
                  </div>

                  <div className="flex-1 min-h-[60px]">
                    {m.status === "generating" && (
                      <div className="flex items-center gap-2 text-xs text-gray-500 font-semibold">
                        <Loader2 className="w-3.5 h-3.5 animate-spin" /> Generating…
                      </div>
                    )}
                    {m.status === "error" && (
                      <div className="flex items-start gap-2 text-xs text-red-700 font-semibold">
                        <AlertTriangle className="w-3.5 h-3.5 shrink-0 mt-0.5" />
                        <span>{m.error || "Generation failed"}</span>
                      </div>
                    )}
                    {m.status === "ready" && (
                      <>
                        <h4 className="text-sm font-bold text-gray-900 leading-tight">{m.title}</h4>
                        <p className="text-xs text-gray-500 mt-1 line-clamp-3 leading-relaxed">{m.description}</p>
                      </>
                    )}
                  </div>

                  <div className="flex items-center justify-between gap-2 pt-2 border-t border-gray-100">
                    <span className="text-[10px] text-gray-400 truncate">{m.modelUsed}</span>
                    <div className="flex items-center gap-1.5 shrink-0">
                      {m.status === "ready" && (
                        <button
                          onClick={() => onView(m)}
                          className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold"
                        >
                          <Eye className="w-3.5 h-3.5" /> View
                        </button>
                      )}
                      <button
                        onClick={() => handleDelete(m)}
                        disabled={deletingId === m.id}
                        className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg bg-white border border-gray-300 hover:bg-gray-50 text-gray-600 text-xs font-bold disabled:opacity-50"
                        title="Discard this version"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        <div className="px-6 py-4 border-t border-gray-200 bg-gray-50 flex items-center justify-end">
          <button
            onClick={onClose}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-bold text-sm"
          >
            <CheckCircle2 className="w-4 h-4" /> Done
          </button>
        </div>
      </div>
    </div>
  );
}
